services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      - backend_uploads:/app/uploads

  admin-panel:
    build:
      context: ./admin-panel
    container_name: admin-panel
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_uploads:
