-- AlterTable
ALTER TABLE `attendance` MODIFY `status` ENUM('PRESENT', 'ABSENT', 'LEAVE', 'SHORT_LEAVE', 'HALF_DAY', 'HOLIDAY') NOT NULL DEFAULT 'PRESENT';

-- AlterTable
ALTER TABLE `staffattendance` MODIFY `status` ENUM('PRESENT', 'ABSENT', 'LEAVE', 'SHORT_LEAVE', 'HALF_DAY', 'HOLIDAY') NOT NULL DEFAULT 'PRESENT';
